EXE = chip8

SOURCES = source/main.cpp source/chip8.cpp source/sdl1_chip8.cpp source/config.cpp
OBJS = $(addsuffix .o, $(basename $(SOURCES)))

CXXFLAGS = -I./include -g -O3 -Wno-unused-result
LIBS = `sdl-config --libs` -lSDL_ttf

%.o:%.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

all: $(EXE)
	@echo Build complete for $(EXE)

$(EXE): $(OBJS)
	$(CXX) -o $@ $^ $(CXXFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) $(EXE)
